blog_db_blue/models.py
# -*- coding: utf-8 -*-

from app import db
from datetime import datetime, date
from wtforms.validators import Email
from flask.ext.babel import gettext
import qrcode
from werkzeug.security import (
    generate_password_hash,
    check_password_hash,
)
from wtforms import widgets
from flask_login import UserMixin


class User(db.Model, UserMixin):
    id = db.Column(db.Integer, primary_key=True, index=True)
    username = db.Column(db.String(80), info={'label': gettext('Name')})
    email = db.Column(
        db.String(100),
        nullable=False,
        unique=True,
        index=True,
        info={
            'validators': Email(),
            'label': u'Эл. почта'
        }
    )
    pswd = db.Column(db.String(200), nullable=False, info={'label': gettext('Password')})

    def set_pswd(self, pswd):
        self.pswd = generate_password_hash(pswd)

    def check_pswd(self, pswd):
        return check_password_hash(self.pswd, pswd)

    def __repr__(self):
        return self.username


class Post(db.Model):
    id = db.Column(db.Integer, primary_key=True, index=True)

    user_id = db.Column(db.Integer, db.ForeignKey('user.id'), index=True)
    user = db.relationship(
        'User', backref=db.backref('posts', lazy='dynamic')
    )

    title = db.Column(db.String(140), unique=True, info={'label': gettext('Title')})
    content = db.Column(db.String(3000), info={'label': gettext('Content'), 'widget': widgets.TextArea()})
    date_created = db.Column(db.Date, default=date.today())
    is_visible = db.Column(db.Boolean, default=True)
    qr_path = db.Column(db.String(200))

    def __init__(self, title='', content='', user=None,
                 date_created=None, is_visible=None):
        self.title = title
        self.content = content
        self.user = user

        path = datetime.now().strftime('%d-%m-%Y-%H-%M-%S') + '.png'
        self.qr_create(title, path)
        self.qr_path = path

        if date_created is not None:
            self.date_created = date_created

        if is_visible is not None:
            self.is_visible = is_visible

    def qr_create(self, to_qr, fname):
        qr = qrcode.QRCode(
            version=1,
            error_correction=qrcode.constants.ERROR_CORRECT_L,
            box_size=10,
            border=4,
        )
        qr.add_data(to_qr)
        qr.make(fit=True)
        img = qr.make_image()
        img.save('static/' + fname)

blog_db_blue/forms.py
# -*- coding: utf-8 -*-

from flask.ext.wtf import Form
from wtforms_alchemy import model_form_factory
from wtforms import PasswordField, StringField
from flask.ext.babel import gettext

from models import User, Post

BaseForm = model_form_factory(Form)

class NewUserFrm(BaseForm):
    pswd1 = PasswordField(gettext('Password'))
    pswd2 = PasswordField(gettext('Repeat password'))
    class Meta:
        model = User
        only = ['username', 'email']

    def validate(self):
        super(NewUserFrm, self)
        if self.pswd1.data == self.pswd2.data:
            return True
        else:
            return False


class EnterUserFrm(BaseForm):
    pswd = PasswordField(gettext('Password'))
    class Meta:
        model = User
        only = ['email']


class NewPostFrm(BaseForm):
    class Meta:
        model = Post
        only = ['title', 'content']

blog_db_blue/app.py
# -*- coding: utf-8 -*-

from flask import Flask, redirect, url_for, session
from flask_sqlalchemy import SQLAlchemy
from flask.ext.login import LoginManager
from flask.ext.babel import Babel
from flask.ext.mail import Mail

import config

login_manager = LoginManager()
db = SQLAlchemy()
mail = Mail()
babel = Babel()

@login_manager.user_loader
def load_user(user_id):
    from models import User
    return User.query.get(user_id)


def create_app():
    from views import auth, user, home

    app = Flask(__name__, template_folder='templates')
    app.config.from_object(config)

    app.register_blueprint(auth)
    app.register_blueprint(user)
    app.register_blueprint(home)

    login_manager.init_app(app)
    db.init_app(app)
    mail.init_app(app)
    babel.init_app(app)

    with app.app_context():
        db.create_all()

    return app


@login_manager.unauthorized_handler
def unauthorized():
    return redirect(url_for('auth.login'))


if __name__ == '__main__':
    app = create_app()

    @babel.localeselector
    def get_locale():
        try:
            l = session['locale']
        except KeyError:
            l = None
            session['locale'] = None
        if l is not None:
            return l
        else:
            return 'en'
    app.run()

blog_db_blue/views.py
# -*- coding: utf-8 -*-

from flask import (
    Blueprint,
    request,
    redirect,
    render_template,
    flash,
    url_for,
    g,
    session,
)
from flask.ext.login import (
    login_required,
    login_user,
    logout_user,
    current_user,
)
from forms import (
    NewUserFrm,
    NewPostFrm,
    EnterUserFrm
)
from models import User, Post
from app import db
from flask_babel import gettext


auth = Blueprint('auth', __name__, url_prefix='/auth')
user = Blueprint('user', __name__, url_prefix='/user')
home = Blueprint('home',__name__)

@home.route('/', methods=['GET', 'POST'])
def main():
    p = Post.query.filter_by(is_visible=True).all()
    return render_template('posts.html', posts=p)


@home.route('/locale', methods=['GET'])
def locale_change():
    loc = session['locale']
    if loc is None:
        loc = 'en'
    else:
        if loc == 'en':
            loc = 'ru'
        else:
            loc = 'en'
    session['locale'] = loc
    flash(gettext('The language is changed'))
    return redirect(url_for('.main'))


@home.route('/cleardb', methods=['GET'])
def cleardb():
    users = User.query.all()
    posts = Post.query.all()
    for post in posts:
        db.session.delete(post)
    for user in users:
        db.session.delete(user)
    db.session.commit()
    return 'Success'

@user.route('/status-post', methods=['POST'])
@login_required
def StatusPost():
    pid = request.form['post_id']
    met = request.form['method']
    if met == 'show':
        status = True
    else:
        status = False
    Post.query.filter_by(id=pid).update({'is_visible': status})
    db.session.commit()
    return redirect(url_for('.myposts'))


@user.route('/myposts', methods=['GET'])
@login_required
def myposts():
    p = current_user.posts.all()
    return render_template('posts.html', posts=p)


@user.route('/newpost', methods=['GET', 'POST'])
@login_required
def newpost():
    if request.method == 'GET':
        frm = NewPostFrm()
    else:
        frm = NewPostFrm(request.form)
        if frm.validate():
            p = Post(user=current_user, **frm.data)
            db.session.add(p)
            db.session.commit()
            flash(gettext('Post is added'))
        else:
            flash(gettext('Validation problem'))
    return render_template('form.html', form=frm, action=url_for('.newpost'))


@user.route('/exit', methods=['GET'])
@login_required
def user_exit():
    logout_user()
    return redirect(url_for('home.main'))


@auth.route('/', methods=['GET', 'POST'])
def login():
    if request.method == 'GET':
        frm = EnterUserFrm()
    else:
        frm = EnterUserFrm(request.form)
        u = User.query.filter_by(email=request.form['email']).first()
        if u and u.check_pswd(request.form['pswd']):
            login_user(u)
            return redirect(url_for('user.myposts'))
        else:
            flash(gettext('Invalid email or password'))
    return render_template('form.html', form=frm, action=url_for('.login'))


@auth.route('/newuser', methods=['GET', 'POST'])
def newuser():
    from flask_mail import Message
    from app import mail
    if request.method == 'GET':
        frm = NewUserFrm()
    else:
        frm = NewUserFrm(request.form)
        if frm.validate():
            u = User()
            frm.populate_obj(u)
            u.set_pswd(frm.pswd1.data)
            db.session.add(u)
            db.session.commit()
            flash('User is added')
            rec = []
            rec.append(frm.email.data)
            msg = Message(gettext("You have registered successfully"),
                  sender="danil3dpy@yandex.ru",
                  recipients=rec)
            msg.body = gettext("The registration in Danil blog is succesfull")
            mail.send(msg)
        else:
            flash('Validation problem')
    return render_template('form.html', form=frm, action=url_for('.newuser'))

blog_db_blue/templates/auth.html
{% extends 'layout.html' %}

{% block auth %}

<h1>sd</h1>

{% endblock %}

blog_db_blue/templates/form.html
{% extends 'layout.html' %}

{% block content %}

    <form method="POST" action="{{ action }}">
        {{form.hidden_tag()}}
        <dl>
            {% for field in form %}
                {% if field.type != 'CSRFTokenField' %}
                    {{field.label}}: {{field}}<br/>
                {% endif %}
            {% endfor %}
        </dl>

        <input type="submit" value="{{ 'Submit' }}" class="btn">
    </form>

{% endblock %}

blog_db_blue/templates/layout.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{%block title%}{%endblock%}</title>
    <style>
        body{font-family:arial;}
        .posts{margin-top:30px;}
        .post{border-top:1px #000 dashed; padding-top:10px; margin-bottom:20px; width:100%; clear:both;}
        .post h1{font-size:18px;}
        .qr{float:left;}
        .user{background:#000000; color:#ffffff; font-weight:bolder; padding:10px 10px;}
        .menu{margin-top:20px;}
        a{color:#0000FF; text-decoration:none;}
        a:hover{border-bottom:1px #000000 dashed;}
        .menu a{margin-left:20px;}
    </style>
</head>
<body>

{% with messages = get_flashed_messages(with_categories=true) %}
        {% if messages %}
            <div class="msg">
            <ul class=flashes>
                {% for category, message in messages %}
                    <li class="{{ category }}">{{ message }}</li>
                {% endfor %}
            </ul>
            </div>
        {% endif %}
{% endwith %}
{% if current_user.is_authenticated %}
<div class="user">{{_('Hi')}}, {{current_user.username}}!</div>
{% endif %}
<div class="menu">
    <a href="{{url_for('home.main')}}">{{_('All posts')}}</a>
    {% if current_user.is_authenticated %}
        <a href="{{url_for('user.myposts')}}">{{_('My Posts')}}</a>
        <a href="{{url_for('user.newpost')}}">{{_('Write Post')}}</a>
        <a href="{{url_for('user.user_exit')}}">{{_('Quit')}}</a>
    {% else %}
        <a href="{{url_for('auth.newuser')}}">{{_('New User')}}</a>
        <a href="{{url_for('auth.login')}}">{{_('Log IN')}}</a>
    {% endif %}
    <a href="{{url_for('home.locale_change')}}">{{_('Switch language')}}</a>
</div>


{% block content %}
{% endblock %}

</body>
</html>

blog_db_blue/templates/posts.html
{% extends 'layout.html' %}

{% block title %} {{_('Posts list')}} {% endblock %}

{% block content %}

{% if username %}
<div>
    <h1>{{_('Hi')}}, {{current_user.username}}!</h1>
    <p>{{_('Here is a list of the posts you published')}}</p>
</div>
{% endif %}


    {% if posts %}
        <div class="posts">
        {% for post in posts %}
            <div class="post">
                {% if post.qr_path %}
           <div class="qr">
               <img src="{{url_for('static', filename=post.qr_path)}}" />
           </div>
            {% endif %}
               <div>
                   <b>{{_('Author')}}: {{post.user.username}}</b> - {{post.date_created}}
               </div>
               <div>
                   <h1>{{post.title}}</h1>
                   <div>{{post.content}}</div>
               </div>
                {% if current_user and current_user.id == post.user.id %}
                        <form action="{{url_for('user.StatusPost')}}" method="post">
                            <input type="hidden" name="post_id" value="{{post.id}}" />
                            <input type="hidden" name="method" value="{% if post.is_visible %}hide{% else %}show{% endif %}" />
                            <input type="submit" value="{% if post.is_visible %}{{_('Hide')}}{% else %}{{_('Show')}}{% endif %}">
                        </form>
                {% endif %}
            </div>
        {% endfor %}
        </div>
    {% else %}
        <h1>{{_('There is no posts yet')}}</h1>
    {% endif %}


{% endblock %}